azae_core:
    resource: "@AzaeCoreBundle/Resources/config/routing.yml"
    type:      annotation
    prefix:   /

oc_platform:
    resource: "@OCPlatformBundle/Controller"
    type:      annotation
    prefix:   /platform

